#!/usr/bin/env python3
"""
Model Comparison Table — All models on the SAME OOS period.

Computes hourly, weekly, monthly MAE + RMSE + directional accuracy
for every model in the pipeline. Prints a clean comparison table.

Models evaluated:
  1. Seasonal Naive 24h   (yesterday same hour)
  2. Seasonal Naive 168h  (last week same hour)
  3. Ridge Regression      (baseline linear model)
  4. LightGBM standalone   (no ensemble, no post-processing)
  5. LGBM+Ridge Ensemble   (best model, full pipeline with AR + EW bias)

Usage:
    cd /Users/harsh/Downloads/cobblestone_project
    .venv/bin/python scripts/run_model_comparison.py

Note: Models 1-4 are trained from scratch (fast, <30s total).
      Model 5 loads saved predictions from oos_predictions.parquet
      (generated by run_forecasting.py).
"""

import sys, warnings
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
from sklearn.linear_model import Ridge
from sklearn.preprocessing import StandardScaler

from src.features import build_feature_matrix
from src.ingestion import DATA_PROCESSED
from src.models import TARGET_COL, OOS_TEST_START, OOS_TEST_END, LGBMRidgeEnsemble, LGBM_PARAMS

# ── Load data ───────────────────────────────────────────────────────
print("Loading data and building features...")
df = pd.read_parquet(DATA_PROCESSED / "de_power_dataset.parquet")
fm = build_feature_matrix(df)

oos_start = pd.Timestamp(OOS_TEST_START, tz="UTC")
oos_end   = pd.Timestamp(f"{OOS_TEST_END} 23:00", tz="UTC")

train = fm.loc[fm.index < oos_start].dropna(subset=[TARGET_COL])
test  = fm.loc[(fm.index >= oos_start) & (fm.index <= oos_end)].dropna(subset=[TARGET_COL])

X_train, y_train = train.drop(columns=[TARGET_COL]), train[TARGET_COL]
X_test,  y_test  = test.drop(columns=[TARGET_COL]),  test[TARGET_COL]

actual = y_test.values
idx    = X_test.index
lag24  = X_test["price_lag_24h"].values
lag168 = X_test["price_lag_168h"].values

print(f"Train: {len(X_train):,}  |  Test: {len(X_test):,}  |  Features: {X_train.shape[1]}")
print(f"OOS: {idx[0].date()} → {idx[-1].date()}")


# ── Metrics helper ──────────────────────────────────────────────────
def compute_all(pred, actual, idx, lag168):
    """Return dict with hourly/weekly/monthly MAE, RMSE, and directional accuracy."""
    m = ~np.isnan(pred) & ~np.isnan(actual)
    p, a = pred[m], actual[m]

    # Hourly
    h_mae  = np.abs(a - p).mean()
    h_rmse = np.sqrt(((a - p)**2).mean())

    # Dir acc vs lag-168h (week-over-week direction)
    l = lag168[m]
    v = ~np.isnan(l)
    ps = np.sign(p[v] - l[v])
    as_ = np.sign(a[v] - l[v])
    nz = (ps != 0) & (as_ != 0)
    h_da = (ps[nz] == as_[nz]).mean() * 100 if nz.sum() > 0 else float("nan")

    # Weekly
    wdf = pd.DataFrame({"a": a, "p": p}, index=idx[m])
    wdf["yr"] = wdf.index.isocalendar().year.astype(int)
    wdf["wk"] = wdf.index.isocalendar().week.astype(int)
    wg = wdf.groupby(["yr", "wk"]).mean()
    w_mae  = np.abs(wg["a"] - wg["p"]).mean()
    w_rmse = np.sqrt(((wg["a"] - wg["p"])**2).mean())

    # Monthly
    wdf["mo"] = wdf.index.to_period("M")
    mg = wdf.groupby("mo").mean()
    m_mae  = np.abs(mg["a"] - mg["p"]).mean()
    m_rmse = np.sqrt(((mg["a"] - mg["p"])**2).mean())

    return {
        "h_mae": h_mae, "h_rmse": h_rmse, "h_da": h_da,
        "w_mae": w_mae, "w_rmse": w_rmse,
        "m_mae": m_mae, "m_rmse": m_rmse,
    }


# ── Model 1: Seasonal Naive 24h ────────────────────────────────────
print("\n[1/5] Seasonal Naive 24h...")
naive24_pred = lag24.copy()
r_naive24 = compute_all(naive24_pred, actual, idx, lag168)

# ── Model 2: Seasonal Naive 168h ───────────────────────────────────
print("[2/5] Seasonal Naive 168h...")
naive168_pred = lag168.copy()
r_naive168 = compute_all(naive168_pred, actual, idx, lag168)

# ── Model 3: Ridge Regression (12 curated fundamentals) ────────────
print("[3/5] Ridge Regression baseline...")
# Use same fundamental features the LinearRegressionBaseline uses
ridge_features = [
    "wind_forecast_mw", "solar_forecast_mw", "load_forecast_mw",
    "gas_price_eur_mwh", "hour_sin", "hour_cos", "month_sin", "month_cos",
    "is_weekend", "price_lag_24h", "price_lag_168h", "residual_load",
]
# Filter to features that exist
ridge_features = [f for f in ridge_features if f in X_train.columns]
X_tr_ridge = X_train[ridge_features].fillna(0)
X_te_ridge = X_test[ridge_features].fillna(0)

scaler = StandardScaler()
X_tr_scaled = scaler.fit_transform(X_tr_ridge)
X_te_scaled = scaler.transform(X_te_ridge)

ridge = Ridge(alpha=10.0)
ridge.fit(X_tr_scaled, y_train)
ridge_pred = ridge.predict(X_te_scaled)
r_ridge = compute_all(ridge_pred, actual, idx, lag168)

# ── Model 4: LightGBM standalone (no Ridge, no AR, no EW bias) ─────
print("[4/5] LightGBM standalone...")
import lightgbm as lgb

lgbm = lgb.LGBMRegressor(**LGBM_PARAMS)
lgbm.fit(X_train.fillna(0), y_train)
lgbm_pred = lgbm.predict(X_test.fillna(0))
r_lgbm = compute_all(lgbm_pred, actual, idx, lag168)

# ── Model 5: LGBM+Ridge+AR+EW (load from saved predictions) ───────
print("[5/5] LGBM+Ridge+AR+EW (loading saved OOS predictions)...")
oos_path = DATA_PROCESSED / "oos_predictions.parquet"
if oos_path.exists():
    oos_df = pd.read_parquet(oos_path)
    oos_df.index = pd.to_datetime(oos_df.index)
    # y_pred is the final best prediction (hourly-EW corrected)
    best_pred = oos_df["y_pred"].reindex(idx).values
    r_best = compute_all(best_pred, actual, idx, lag168)
else:
    print("  WARNING: oos_predictions.parquet not found!")
    print("  Run 'python scripts/run_forecasting.py' first to generate it.")
    r_best = {k: float("nan") for k in ["h_mae", "h_rmse", "h_da", "w_mae", "w_rmse", "m_mae", "m_rmse"]}

# ── Print table ─────────────────────────────────────────────────────
results = [
    ("Seasonal Naive (24h)",          r_naive24),
    ("Seasonal Naive (168h)",         r_naive168),
    ("Ridge Regression",              r_ridge),
    ("LightGBM (standalone)",         r_lgbm),
    ("LGBM+Ridge+AR+EW (best)",      r_best),
]

print(f"\n{'='*100}")
print(f"  MODEL COMPARISON — OOS: {idx[0].date()} → {idx[-1].date()} ({len(X_test):,} hours)")
print(f"{'='*100}")
print()

# Header
h = f"  {'Model':<30s} | {'Hourly MAE':>10s} {'RMSE':>8s} {'Dir.Acc':>8s} | {'Weekly MAE':>10s} {'RMSE':>8s} | {'Monthly MAE':>11s} {'RMSE':>8s}"
print(h)
print(f"  {'-'*96}")

for name, r in results:
    da_str = f"{r['h_da']:.1f}%" if not np.isnan(r['h_da']) else "N/A"
    print(f"  {name:<30s} | {r['h_mae']:>10.2f} {r['h_rmse']:>8.2f} {da_str:>8s} | {r['w_mae']:>10.2f} {r['w_rmse']:>8.2f} | {r['m_mae']:>11.2f} {r['m_rmse']:>8.2f}")

print(f"  {'-'*96}")
print()

# Skill scores vs naive-168h
naive168_mae = r_naive168["h_mae"]
print("  Skill Score vs Naive-168h (hourly MAE reduction):")
for name, r in results:
    if name == "Seasonal Naive (168h)":
        continue
    skill = 1 - r["h_mae"] / naive168_mae
    pct = (naive168_mae - r["h_mae"]) / naive168_mae * 100
    print(f"    {name:<30s}  skill = {skill:+.3f}  ({pct:+.1f}%)")

print(f"\n{'='*100}")
print("  Note: Dir.Acc = directional accuracy vs week-ago price (lag-168h)")
print("        Weekly/Monthly = mean of weekly/monthly average price predictions")
print(f"{'='*100}")
